


Test: Handler Factory test.cpp
	g++ -std=c++11 -I ../include test.cpp isockHandler isockFactory

Handler:ISocketHandler.cpp
	g++ -c -std=c++11 -I ../include ISocketHandler.cpp -o isockHandler

Factory:ISocketFactory.cpp
	g++ -c -std=c++11 -I ../include ISocketFactory.cpp -o isockFactory
