CC=gcc
LIB=-L/home/umit/LinuxSocketProgramming/SocketAPI/
INCLUDE=-I/home/umit/LinuxSocketProgramming/SocketAPI/include
LIBNAME=-ltcpsocket -lpthread
SRC=file_server.c

Server: file_server.c
	$(CC) $(SRC) $(INCLUDE) $(LIB) $(LIBNAME) -o server
